jdbc:postgresql://host.containers.internal:5433/users
quarkus.datasource.username=postgres
quarkus.datasource.password=123
quarkus.hibernate-orm.database.generation=update
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.user-created-out.connector=smallrye-kafka
mp.messaging.outgoing.user-created-out.topic=user-created
mp.messaging.outgoing.user-created-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
